require('dotenv').config();
const mongoose = require('mongoose');
const Question = require('./models/Question');
const Topic = require('./models/Topic');

const seedQuestions = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('MongoDB Connected!');

    // Get all topics
    const topics = await Topic.find();
    if (topics.length === 0) {
      console.log('No topics found! Please add topics first.');
      process.exit();
    }

    console.log('Found topics:');
    topics.forEach((t, i) => console.log(`${i + 1}. ${t.title} (${t.category}) - ID: ${t._id}`));

    const getTopicId = (category) => {
      const topic = topics.find(t => t.category === category);
      return topic ? topic._id : null;
    };

    // Clear existing questions
    await Question.deleteMany({});
    console.log('Cleared existing questions...');

    const questions = [

      // ── SRC QUESTIONS ─────────────────────────────────────────
      { topicId: getTopicId('SRC'), questionText: 'What does SRC stand for?', options: ['Student Recreation Council', 'Student Representative Council', 'Student Regulatory Committee', 'Student Resource Center'], correctAnswer: 'Student Representative Council', order: 1 },
      { topicId: getTopicId('SRC'), questionText: 'What is the primary role of the SRC at Crawford University?', options: ['To manage university finances', 'To serve as a bridge between students and university management', 'To organize only sporting events', 'To handle staff welfare'], correctAnswer: 'To serve as a bridge between students and university management', order: 2 },
      { topicId: getTopicId('SRC'), questionText: 'Who is the head of the SRC?', options: ['The Vice Chancellor', 'The Dean of Student Affairs', 'The SRC President', 'The Financial Secretary'], correctAnswer: 'The SRC President', order: 3 },
      { topicId: getTopicId('SRC'), questionText: 'Which of the following is NOT a responsibility of the SRC?', options: ['Representing student interests', 'Organizing student programs', 'Managing student academic results', 'Supporting new students during orientation'], correctAnswer: 'Managing student academic results', order: 4 },
      { topicId: getTopicId('SRC'), questionText: 'How can students raise issues with university management through the SRC?', options: ['By writing directly to the Vice Chancellor', 'Through town hall meetings organized by the SRC', 'By posting on social media', 'By contacting JAMB'], correctAnswer: 'Through town hall meetings organized by the SRC', order: 5 },
      { topicId: getTopicId('SRC'), questionText: 'Which of the following is a position in the SRC structure?', options: ['Head of Department', 'Dean of Faculty', 'Public Relations Officer', 'University Bursar'], correctAnswer: 'Public Relations Officer', order: 6 },
      { topicId: getTopicId('SRC'), questionText: 'How are SRC executives selected?', options: ['They are appointed by the Vice Chancellor', 'They are selected by the Registrar', 'They are elected by the student body', 'They are chosen by the DSA'], correctAnswer: 'They are elected by the student body', order: 7 },
      { topicId: getTopicId('SRC'), questionText: 'What should a student do if they have a complaint about campus facilities?', options: ['Ignore it', 'Contact the SRC for support and representation', 'Leave the university', 'Report directly to the government'], correctAnswer: 'Contact the SRC for support and representation', order: 8 },
      { topicId: getTopicId('SRC'), questionText: 'The SRC serves students throughout which period?', options: ['Only during orientation', 'Only in final year', 'Throughout their entire time on campus', 'Only during examinations'], correctAnswer: 'Throughout their entire time on campus', order: 9 },
      { topicId: getTopicId('SRC'), questionText: 'Which of the following best describes the SRC\'s relationship with university management?', options: ['They are in constant conflict', 'They collaborate to improve student life', 'They have no relationship', 'The SRC controls university management'], correctAnswer: 'They collaborate to improve student life', order: 10 },
      { topicId: getTopicId('SRC'), questionText: 'Where is the SRC office located?', options: ['Outside the university', 'On campus', 'At the JAMB office', 'At the state ministry of education'], correctAnswer: 'On campus', order: 11 },
      { topicId: getTopicId('SRC'), questionText: 'What is the SRC\'s role during freshers\' orientation?', options: ['To collect school fees', 'To formally introduce themselves and welcome new students', 'To conduct examinations', 'To distribute hostel keys'], correctAnswer: 'To formally introduce themselves and welcome new students', order: 12 },
      { topicId: getTopicId('SRC'), questionText: 'Which of the following is TRUE about the SRC?', options: ['They only represent final year students', 'They represent the interests of all students', 'They only handle sports activities', 'They are managed by university lecturers'], correctAnswer: 'They represent the interests of all students', order: 13 },
      { topicId: getTopicId('SRC'), questionText: 'What type of meetings does the SRC organize for students to raise issues?', options: ['Board meetings', 'Senate meetings', 'Town hall meetings', 'Faculty meetings'], correctAnswer: 'Town hall meetings', order: 14 },
      { topicId: getTopicId('SRC'), questionText: 'Which position in the SRC handles financial matters?', options: ['President', 'Secretary General', 'Public Relations Officer', 'Financial Secretary'], correctAnswer: 'Financial Secretary', order: 15 },
      { topicId: getTopicId('SRC'), questionText: 'What is the SRC\'s goal for student life at Crawford University?', options: ['To make it more difficult', 'To make it easier and more enjoyable', 'To restrict student activities', 'To monitor student social media'], correctAnswer: 'To make it easier and more enjoyable', order: 16 },
      { topicId: getTopicId('SRC'), questionText: 'Who do Faculty Representatives in the SRC represent?', options: ['University lecturers', 'Students from each college within the university', 'The university management', 'External organizations'], correctAnswer: 'Students from each college within the university', order: 17 },
      { topicId: getTopicId('SRC'), questionText: 'What should new students do to get the most from the SRC?', options: ['Avoid the SRC entirely', 'Actively participate in student governance', 'Only contact SRC during emergencies', 'Wait until final year'], correctAnswer: 'Actively participate in student governance', order: 18 },
      { topicId: getTopicId('SRC'), questionText: 'Which of the following is a key function of the SRC Secretary General?', options: ['Managing student finances', 'Handling official correspondence and records of the council', 'Organizing sports events only', 'Conducting medical checkups'], correctAnswer: 'Handling official correspondence and records of the council', order: 19 },
      { topicId: getTopicId('SRC'), questionText: 'Why is it important for students to know about the SRC?', options: ['Because it is compulsory to pay SRC dues', 'Because the SRC can support and represent them throughout university life', 'Because the SRC controls academic results', 'Because the SRC manages hostel allocation only'], correctAnswer: 'Because the SRC can support and represent them throughout university life', order: 20 },

      // ── LIBRARY QUESTIONS ──────────────────────────────────────
      { topicId: getTopicId('Library'), questionText: 'What are the opening hours of the Crawford University Library?', options: ['8am to 8pm Monday to Friday', '9am to 9pm Monday to Saturday', '7am to 7pm Monday to Sunday', '10am to 6pm Monday to Friday'], correctAnswer: '9am to 9pm Monday to Saturday', order: 1 },
      { topicId: getTopicId('Library'), questionText: 'What must every student obtain before accessing the library?', options: ['A student handbook', 'A library pass', 'A reading permit', 'A faculty ID'], correctAnswer: 'A library pass', order: 2 },
      { topicId: getTopicId('Library'), questionText: 'Which of the following is strictly prohibited in the library?', options: ['Reading textbooks', 'Using a laptop', 'Bringing food and drinks', 'Taking notes'], correctAnswer: 'Bringing food and drinks', order: 3 },
      { topicId: getTopicId('Library'), questionText: 'What dress code is required when visiting the library?', options: ['Casual dressing', 'Sports wear', 'Corporate dressing', 'Traditional attire only'], correctAnswer: 'Corporate dressing', order: 4 },
      { topicId: getTopicId('Library'), questionText: 'What is GST 109?', options: ['A chemistry course', 'Use of Library — a compulsory course for all fresh students', 'A mathematics course', 'An optional elective course'], correctAnswer: 'Use of Library — a compulsory course for all fresh students', order: 5 },
      { topicId: getTopicId('Library'), questionText: 'Which students are required to register for GST 109?', options: ['Final year students only', 'Postgraduate students', 'All 100 level fresh students', 'Only science students'], correctAnswer: 'All 100 level fresh students', order: 6 },
      { topicId: getTopicId('Library'), questionText: 'What must final year students obtain from the library before graduation?', options: ['A recommendation letter', 'Library clearance', 'A reading certificate', 'A book donation receipt'], correctAnswer: 'Library clearance', order: 7 },
      { topicId: getTopicId('Library'), questionText: 'When is the Crawford University Library closed?', options: ['Every Monday', 'Every Saturday', 'Sundays and public holidays', 'Every Wednesday'], correctAnswer: 'Sundays and public holidays', order: 8 },
      { topicId: getTopicId('Library'), questionText: 'What is the purpose of the e-library?', options: ['To provide physical books only', 'To allow students access digital academic resources online', 'To replace the physical library entirely', 'To provide entertainment content'], correctAnswer: 'To allow students access digital academic resources online', order: 9 },
      { topicId: getTopicId('Library'), questionText: 'When is the e-library available?', options: ['Only during library opening hours', 'Monday to Friday only', '24 hours a day, 7 days a week', 'Only on weekends'], correctAnswer: '24 hours a day, 7 days a week', order: 10 },
      { topicId: getTopicId('Library'), questionText: 'Why are food and drinks not allowed in the library?', options: ['Because students should eat in the cafeteria', 'To avoid the destruction of books and library materials', 'Because the library has no space for food', 'To prevent noise making'], correctAnswer: 'To avoid the destruction of books and library materials', order: 11 },
      { topicId: getTopicId('Library'), questionText: 'What should students do with their mobile phones in the library?', options: ['Leave them outside', 'Set them to silent mode', 'Use them freely', 'Switch them off completely'], correctAnswer: 'Set them to silent mode', order: 12 },
      { topicId: getTopicId('Library'), questionText: 'What happens if a student fails to obtain library clearance before graduation?', options: ['They pay a small fine', 'They will not be permitted to collect results, transcripts, or certificates', 'Nothing happens', 'They repeat a year'], correctAnswer: 'They will not be permitted to collect results, transcripts, or certificates', order: 13 },
      { topicId: getTopicId('Library'), questionText: 'What credentials do students need to access the e-library?', options: ['Their JAMB number', 'Their student credentials', 'Their national ID number', 'Their phone number'], correctAnswer: 'Their student credentials', order: 14 },
      { topicId: getTopicId('Library'), questionText: 'Which of the following is a topic covered in GST 109?', options: ['How to play musical instruments', 'Research and referencing skills', 'How to cook Nigerian meals', 'How to drive a car'], correctAnswer: 'Research and referencing skills', order: 15 },
      { topicId: getTopicId('Library'), questionText: 'What is the Dewey Decimal Classification System used for?', options: ['Grading student assignments', 'Organizing and classifying library books and materials', 'Registering students for courses', 'Managing student fees'], correctAnswer: 'Organizing and classifying library books and materials', order: 16 },
      { topicId: getTopicId('Library'), questionText: 'What is expected of students regarding noise in the library?', options: ['Moderate noise is allowed', 'Noise making is strictly prohibited', 'Students can talk freely', 'Only whispering is prohibited'], correctAnswer: 'Noise making is strictly prohibited', order: 17 },
      { topicId: getTopicId('Library'), questionText: 'What is the consequence of damaging library property?', options: ['A verbal warning only', 'Disciplinary action', 'Payment of library fees', 'Temporary suspension of library pass'], correctAnswer: 'Disciplinary action', order: 18 },
      { topicId: getTopicId('Library'), questionText: 'When should final year students begin the library clearance process?', options: ['On the last day of school', 'Well in advance of their graduation', 'After receiving their results', 'During examination period'], correctAnswer: 'Well in advance of their graduation', order: 19 },
      { topicId: getTopicId('Library'), questionText: 'What must a student present at the library entrance during every visit?', options: ['Their course registration form', 'Their library pass', 'Their JAMB slip', 'Their tuition fee receipt'], correctAnswer: 'Their library pass', order: 20 },

      // ── DSA QUESTIONS ──────────────────────────────────────────
      { topicId: getTopicId('DSA'), questionText: 'What does DSA stand for?', options: ['Department of Student Administration', 'Department of Student Affairs', 'Division of Student Activities', 'Department of Social Affairs'], correctAnswer: 'Department of Student Affairs', order: 1 },
      { topicId: getTopicId('DSA'), questionText: 'What is the primary responsibility of the DSA?', options: ['Managing student academic results', 'Overseeing student welfare, discipline and general conduct', 'Handling university finances', 'Organizing sporting events'], correctAnswer: 'Overseeing student welfare, discipline and general conduct', order: 2 },
      { topicId: getTopicId('DSA'), questionText: 'Which of the following is a disciplinary measure that may be taken by the DSA?', options: ['Scholarship award', 'Promotion to the next level', 'Suspension or expulsion', 'Award of extra marks'], correctAnswer: 'Suspension or expulsion', order: 3 },
      { topicId: getTopicId('DSA'), questionText: 'Which of the following behaviors may result in disciplinary action by the DSA?', options: ['Regular class attendance', 'Examination malpractice', 'Submitting assignments on time', 'Participating in chapel'], correctAnswer: 'Examination malpractice', order: 4 },
      { topicId: getTopicId('DSA'), questionText: 'What does the DSA coordinate during the academic session?', options: ['Examination timetables', 'Student orientation programs and hostel allocation', 'Lecturer schedules', 'University budget planning'], correctAnswer: 'Student orientation programs and hostel allocation', order: 5 },
      { topicId: getTopicId('DSA'), questionText: 'What should students do if they have welfare or safety concerns?', options: ['Post about it on social media', 'Report it promptly to the DSA', 'Ignore the concerns', 'Contact JAMB'], correctAnswer: 'Report it promptly to the DSA', order: 6 },
      { topicId: getTopicId('DSA'), questionText: 'Which of the following is strictly prohibited according to DSA rules?', options: ['Attending chapel services', 'Participating in student elections', 'Vandalism and fighting', 'Joining student clubs'], correctAnswer: 'Vandalism and fighting', order: 7 },
      { topicId: getTopicId('DSA'), questionText: 'What is expected of all students regarding university rules?', options: ['To follow only rules they agree with', 'To strictly adhere to all university rules and regulations', 'To follow rules only during examinations', 'To follow rules only in the first year'], correctAnswer: 'To strictly adhere to all university rules and regulations', order: 8 },
      { topicId: getTopicId('DSA'), questionText: 'What does the DSA monitor within the campus environment?', options: ['Student social media accounts', 'Student conduct and compliance with university policies', 'Student bank accounts', 'Student travel plans'], correctAnswer: 'Student conduct and compliance with university policies', order: 9 },
      { topicId: getTopicId('DSA'), questionText: 'Which of the following values does Crawford University expect students to uphold?', options: ['Competition and rivalry', 'Honesty, integrity, respect and responsibility', 'Independence from all rules', 'Financial success only'], correctAnswer: 'Honesty, integrity, respect and responsibility', order: 10 },
      { topicId: getTopicId('DSA'), questionText: 'What is indecent dressing considered at Crawford University?', options: ['A minor issue', 'A personal choice', 'A violation of university policy', 'An acceptable practice'], correctAnswer: 'A violation of university policy', order: 11 },
      { topicId: getTopicId('DSA'), questionText: 'Who should students respect according to DSA guidelines?', options: ['Only senior students', 'Only university lecturers', 'Authority, fellow students and university property', 'Only the Vice Chancellor'], correctAnswer: 'Authority, fellow students and university property', order: 12 },
      { topicId: getTopicId('DSA'), questionText: 'What does the DSA handle regarding student identification?', options: ['Issuing JAMB results', 'Student identification processes', 'National ID card production', 'Voter registration'], correctAnswer: 'Student identification processes', order: 13 },
      { topicId: getTopicId('DSA'), questionText: 'What is the consequence of possession of prohibited items on campus?', options: ['A warning letter only', 'Disciplinary action by the DSA', 'Payment of a fine', 'Community service'], correctAnswer: 'Disciplinary action by the DSA', order: 14 },
      { topicId: getTopicId('DSA'), questionText: 'How should students conduct themselves to reflect university values?', options: ['By following only popular trends', 'In a manner that reflects the values and standards of the university', 'By prioritizing social activities over academics', 'By avoiding all campus activities'], correctAnswer: 'In a manner that reflects the values and standards of the university', order: 15 },
      { topicId: getTopicId('DSA'), questionText: 'What type of behavior is considered immoral conduct at Crawford University?', options: ['Regular library visits', 'Chapel attendance', 'Any form of immoral behavior prohibited by university policy', 'Participating in orientation'], correctAnswer: 'Any form of immoral behavior prohibited by university policy', order: 16 },
      { topicId: getTopicId('DSA'), questionText: 'What role does the DSA play in campus activities?', options: ['It has no role in campus activities', 'It coordinates and monitors student activities on campus', 'It only manages academic activities', 'It only manages sporting activities'], correctAnswer: 'It coordinates and monitors student activities on campus', order: 17 },
      { topicId: getTopicId('DSA'), questionText: 'What should students do to maintain peace and order on campus?', options: ['Report all their classmates to authorities', 'Maintain discipline and respect within the university community', 'Avoid attending university events', 'Only follow rules when lecturers are present'], correctAnswer: 'Maintain discipline and respect within the university community', order: 18 },
      { topicId: getTopicId('DSA'), questionText: 'Which of the following offenses may lead to expulsion from Crawford University?', options: ['Missing one lecture', 'Severe misconduct or examination malpractice', 'Arriving late to class once', 'Forgetting a textbook'], correctAnswer: 'Severe misconduct or examination malpractice', order: 19 },
      { topicId: getTopicId('DSA'), questionText: 'What is the DSA\'s overall goal at Crawford University?', options: ['To restrict student freedom', 'To maintain order and support student welfare throughout university life', 'To manage university finances', 'To replace the role of lecturers'], correctAnswer: 'To maintain order and support student welfare throughout university life', order: 20 },

      // ── CLINIC QUESTIONS ───────────────────────────────────────
      { topicId: getTopicId('Clinic'), questionText: 'What are the operating hours of the Crawford University Health Centre?', options: ['8am to 5pm Monday to Friday', '9am to 9pm Monday to Saturday', '24 hours a day', 'Only during weekdays'], correctAnswer: '24 hours a day', order: 1 },
      { topicId: getTopicId('Clinic'), questionText: 'Where is the Crawford University Health Centre located?', options: ['Inside the library', 'Opposite the school complex beside the general boys hostel', 'Behind the administrative block', 'Next to the sports complex'], correctAnswer: 'Opposite the school complex beside the general boys hostel', order: 2 },
      { topicId: getTopicId('Clinic'), questionText: 'What are newly admitted students required to do at the Health Centre?', options: ['Pay a medical fee', 'Register and undergo medical screening', 'Collect a medical handbook', 'Submit their JAMB results'], correctAnswer: 'Register and undergo medical screening', order: 3 },
      { topicId: getTopicId('Clinic'), questionText: 'Why should students be honest about existing medical conditions during registration?', options: ['To get special treatment', 'To enable medical staff to deliver appropriate care in emergencies', 'To avoid paying for treatment', 'It is not necessary to disclose'], correctAnswer: 'To enable medical staff to deliver appropriate care in emergencies', order: 4 },
      { topicId: getTopicId('Clinic'), questionText: 'Which of the following services is provided by the Health Centre?', options: ['Academic counseling', 'Emergency medical care', 'Hostel allocation', 'Library services'], correctAnswer: 'Emergency medical care', order: 5 },
      { topicId: getTopicId('Clinic'), questionText: 'What should students carry when visiting the clinic?', options: ['Their course registration form', 'Their student identification card', 'Their library pass', 'Their JAMB slip'], correctAnswer: 'Their student identification card', order: 6 },
      { topicId: getTopicId('Clinic'), questionText: 'When should students seek medical attention?', options: ['Only during emergencies', 'Immediately whenever they feel unwell', 'Only at the end of the semester', 'Only when referred by a lecturer'], correctAnswer: 'Immediately whenever they feel unwell', order: 7 },
      { topicId: getTopicId('Clinic'), questionText: 'Which of the following is a service offered by the Health Centre?', options: ['Academic tutoring', 'Health education and counseling', 'Sports coaching', 'Hostel management'], correctAnswer: 'Health education and counseling', order: 8 },
      { topicId: getTopicId('Clinic'), questionText: 'Why is early presentation at the clinic important?', options: ['To avoid long queues', 'To prevent complications and ensure proper diagnosis and treatment', 'To get free medication', 'To avoid missing lectures'], correctAnswer: 'To prevent complications and ensure proper diagnosis and treatment', order: 9 },
      { topicId: getTopicId('Clinic'), questionText: 'What information must students disclose during medical registration?', options: ['Their academic grades', 'Existing medical conditions, allergies and ongoing treatments', 'Their family income', 'Their social media handles'], correctAnswer: 'Existing medical conditions, allergies and ongoing treatments', order: 10 },
      { topicId: getTopicId('Clinic'), questionText: 'Which of the following promotes good health according to the Health Centre guidelines?', options: ['Skipping meals regularly', 'Eating balanced meals and getting adequate rest', 'Staying up all night studying', 'Avoiding all physical activities'], correctAnswer: 'Eating balanced meals and getting adequate rest', order: 11 },
      { topicId: getTopicId('Clinic'), questionText: 'What does the Health Centre provide during medical screening?', options: ['Academic assessment', 'Basic health tests to assess student health condition', 'Financial assessment', 'Psychological profiling'], correctAnswer: 'Basic health tests to assess student health condition', order: 12 },
      { topicId: getTopicId('Clinic'), questionText: 'What type of care does the Health Centre provide for minor illnesses?', options: ['No treatment for minor illnesses', 'Treatment of minor illnesses and injuries', 'Referral to external hospitals only', 'Traditional medicine only'], correctAnswer: 'Treatment of minor illnesses and injuries', order: 13 },
      { topicId: getTopicId('Clinic'), questionText: 'Why should students familiarize themselves with the location of the Health Centre?', options: ['To know where to avoid on campus', 'To easily access medical services during emergencies', 'Because it is close to the cafeteria', 'Because attendance is marked there'], correctAnswer: 'To easily access medical services during emergencies', order: 14 },
      { topicId: getTopicId('Clinic'), questionText: 'Which of the following is a preventive health service offered by the clinic?', options: ['Examination supervision', 'Preventive health services and health education', 'Library orientation', 'Course registration assistance'], correctAnswer: 'Preventive health services and health education', order: 15 },
      { topicId: getTopicId('Clinic'), questionText: 'What records does the Health Centre establish during new student registration?', options: ['Academic records', 'Medical records for future reference', 'Financial records', 'Hostel records'], correctAnswer: 'Medical records for future reference', order: 16 },
      { topicId: getTopicId('Clinic'), questionText: 'What is one of the recommended practices for maintaining good health on campus?', options: ['Eating junk food regularly', 'Participating in physical activities', 'Staying indoors at all times', 'Skipping breakfast daily'], correctAnswer: 'Participating in physical activities', order: 17 },
      { topicId: getTopicId('Clinic'), questionText: 'Which of the following does the Health Centre NOT provide?', options: ['Medical consultation', 'Laboratory tests', 'Academic grade correction', 'Emergency care'], correctAnswer: 'Academic grade correction', order: 18 },
      { topicId: getTopicId('Clinic'), questionText: 'What should students do immediately upon arriving on campus regarding the clinic?', options: ['Visit the clinic for medication', 'Familiarize themselves with the location of the Health Centre', 'Register for medical insurance', 'Avoid the clinic unless very ill'], correctAnswer: 'Familiarize themselves with the location of the Health Centre', order: 19 },
      { topicId: getTopicId('Clinic'), questionText: 'What is the Health Centre\'s commitment to students and staff?', options: ['Providing free accommodation', 'Providing quality medical care and health services', 'Managing student academic records', 'Providing financial assistance'], correctAnswer: 'Providing quality medical care and health services', order: 20 },

      // ── REGISTRAR QUESTIONS ────────────────────────────────────
      { topicId: getTopicId('Registrar'), questionText: 'What is the primary role of the Registrar\'s Office?', options: ['Managing student social activities', 'Managing student records, admissions, and academic documentation', 'Organizing sporting events', 'Providing medical services'], correctAnswer: 'Managing student records, admissions, and academic documentation', order: 1 },
      { topicId: getTopicId('Registrar'), questionText: 'Which document serves as official proof of admission into Crawford University?', options: ['O\'Level Result', 'Birth Certificate', 'JAMB Admission Letter', 'Acceptance Fee Receipt'], correctAnswer: 'JAMB Admission Letter', order: 2 },
      { topicId: getTopicId('Registrar'), questionText: 'Which of the following is a required admission document?', options: ['Bank statement', 'Passport photographs', 'Social media handle', 'Voter registration card'], correctAnswer: 'Passport photographs', order: 3 },
      { topicId: getTopicId('Registrar'), questionText: 'What should students do if there are errors in their personal information?', options: ['Ignore the errors', 'Report immediately to the Admissions Office for correction', 'Wait until graduation to correct it', 'Contact WAEC directly'], correctAnswer: 'Report immediately to the Admissions Office for correction', order: 4 },
      { topicId: getTopicId('Registrar'), questionText: 'What may happen if personal information errors are not corrected early?', options: ['Nothing happens', 'Serious complications during graduation or certificate issuance', 'The student receives a bonus', 'The university corrects it automatically'], correctAnswer: 'Serious complications during graduation or certificate issuance', order: 5 },
      { topicId: getTopicId('Registrar'), questionText: 'Through which body must students confirm their admission status?', options: ['NUC', 'WAEC', 'JAMB', 'The university senate'], correctAnswer: 'JAMB', order: 6 },
      { topicId: getTopicId('Registrar'), questionText: 'What must newly admitted students do before being fully registered?', options: ['Pay SRC dues', 'Visit the Admissions Office to complete documentation and verification', 'Register for elective courses only', 'Collect their hostel key first'], correctAnswer: 'Visit the Admissions Office to complete documentation and verification', order: 7 },
      { topicId: getTopicId('Registrar'), questionText: 'What is the role of the Registrar\'s Office in academic processes?', options: ['To ensure academic processes comply with university policies and national standards', 'To manage student social events', 'To handle student disciplinary cases only', 'To provide medical services'], correctAnswer: 'To ensure academic processes comply with university policies and national standards', order: 8 },
      { topicId: getTopicId('Registrar'), questionText: 'Which of the following is NOT a required admission document?', options: ['JAMB Result Slip', 'O\'Level Result', 'Voter registration card', 'Birth Certificate'], correctAnswer: 'Voter registration card', order: 9 },
      { topicId: getTopicId('Registrar'), questionText: 'What should students do with their important academic documents?', options: ['Leave them at home', 'Keep multiple copies and store them safely', 'Submit all originals to the university permanently', 'Share them on social media'], correctAnswer: 'Keep multiple copies and store them safely', order: 10 },
      { topicId: getTopicId('Registrar'), questionText: 'What type of errors must be reported to the Admissions Office immediately?', options: ['Errors in social media profiles', 'Name corrections, spelling errors and date of birth discrepancies', 'Errors in sports results', 'Errors in hostel room assignments'], correctAnswer: 'Name corrections, spelling errors and date of birth discrepancies', order: 11 },
      { topicId: getTopicId('Registrar'), questionText: 'What does the Registrar\'s Office manage regarding students and university administration?', options: ['Sports management', 'Official communication between students and university administration', 'Hostel management', 'Cafeteria management'], correctAnswer: 'Official communication between students and university administration', order: 12 },
      { topicId: getTopicId('Registrar'), questionText: 'Which of the following must be completed promptly by newly admitted students?', options: ['SRC membership registration', 'All admission requirements and documentation', 'Sports team registration', 'Club membership forms'], correctAnswer: 'All admission requirements and documentation', order: 13 },
      { topicId: getTopicId('Registrar'), questionText: 'What is the JAMB Result Slip used for during admission?', options: ['As proof of O\'Level results', 'As part of required admission documentation', 'As a library pass', 'As a hostel allocation form'], correctAnswer: 'As part of required admission documentation', order: 14 },
      { topicId: getTopicId('Registrar'), questionText: 'Why is the JAMB Admission Letter important?', options: ['It is not very important', 'It serves as official proof of admission into the university', 'It is only needed for hostel allocation', 'It replaces the O\'Level result'], correctAnswer: 'It serves as official proof of admission into the university', order: 15 },
      { topicId: getTopicId('Registrar'), questionText: 'What is the Acceptance Fee Receipt used for?', options: ['As proof of payment of the acceptance fee during admission', 'As a library pass', 'As a course registration form', 'As proof of JAMB examination'], correctAnswer: 'As proof of payment of the acceptance fee during admission', order: 16 },
      { topicId: getTopicId('Registrar'), questionText: 'What does the Registrar\'s Office ensure regarding educational standards?', options: ['That students pass all examinations', 'That academic processes comply with national educational standards', 'That all students receive scholarships', 'That sports activities are properly funded'], correctAnswer: 'That academic processes comply with national educational standards', order: 17 },
      { topicId: getTopicId('Registrar'), questionText: 'What document confirms a student\'s age during admission?', options: ['Voter registration card', 'Birth Certificate or Declaration of Age', 'National ID card', 'Driver\'s license'], correctAnswer: 'Birth Certificate or Declaration of Age', order: 18 },
      { topicId: getTopicId('Registrar'), questionText: 'When should students complete their admission documentation?', options: ['Before the end of their first year', 'Promptly and accurately upon admission', 'Only when requested by lecturers', 'During final year clearance'], correctAnswer: 'Promptly and accurately upon admission', order: 19 },
      { topicId: getTopicId('Registrar'), questionText: 'Which office do students visit to complete admission documentation?', options: ['The DSA office', 'The Admissions Office under the Registrar', 'The SRC office', 'The library administration desk'], correctAnswer: 'The Admissions Office under the Registrar', order: 20 },

      // ── SECURITY QUESTIONS ─────────────────────────────────────
      { topicId: getTopicId('Security'), questionText: 'What is the primary role of the University Security Unit?', options: ['Managing student academic records', 'Maintaining safety, order and protection of lives and property', 'Organizing student events', 'Providing medical services'], correctAnswer: 'Maintaining safety, order and protection of lives and property', order: 1 },
      { topicId: getTopicId('Security'), questionText: 'What must every student carry on campus at all times?', options: ['Their library pass', 'Their student identification card', 'Their JAMB result slip', 'Their course registration form'], correctAnswer: 'Their student identification card', order: 2 },
      { topicId: getTopicId('Security'), questionText: 'What must visitors do before entering the university campus?', options: ['Pay an entrance fee', 'Register at the security gate', 'Contact the DSA first', 'Obtain a library pass'], correctAnswer: 'Register at the security gate', order: 3 },
      { topicId: getTopicId('Security'), questionText: 'Which of the following is strictly prohibited on campus?', options: ['Attending chapel services', 'Joining student clubs', 'Theft and vandalism', 'Visiting the library'], correctAnswer: 'Theft and vandalism', order: 4 },
      { topicId: getTopicId('Security'), questionText: 'What should students do when they notice suspicious activities on campus?', options: ['Ignore it', 'Report it immediately to the security unit', 'Post about it on social media', 'Handle it themselves'], correctAnswer: 'Report it immediately to the security unit', order: 5 },
      { topicId: getTopicId('Security'), questionText: 'What do security personnel conduct to monitor student activities?', options: ['Academic assessments', 'Routine patrols', 'Medical checkups', 'Library inspections'], correctAnswer: 'Routine patrols', order: 6 },
      { topicId: getTopicId('Security'), questionText: 'What are students required to observe regarding hostel regulations?', options: ['No regulations apply to hostels', 'Hostel entry and exit regulations', 'Students can enter and exit at any time', 'Only senior students follow hostel regulations'], correctAnswer: 'Hostel entry and exit regulations', order: 7 },
      { topicId: getTopicId('Security'), questionText: 'How should students cooperate with security personnel?', options: ['By ignoring their instructions', 'By cooperating fully with them at all times', 'By cooperating only when convenient', 'By reporting them to university management'], correctAnswer: 'By cooperating fully with them at all times', order: 8 },
      { topicId: getTopicId('Security'), questionText: 'What items are prohibited from being brought into the university?', options: ['Textbooks and laptops', 'Prohibited items as specified by university policy', 'Personal hygiene products', 'Food from outside campus'], correctAnswer: 'Prohibited items as specified by university policy', order: 9 },
      { topicId: getTopicId('Security'), questionText: 'Which of the following is a security rule at Crawford University?', options: ['Students may enter without ID', 'Visitors can enter without registration', 'Students must always carry their student ID card', 'Fighting is allowed in self defense'], correctAnswer: 'Students must always carry their student ID card', order: 10 },
      { topicId: getTopicId('Security'), questionText: 'How does the Security Unit contribute to campus life?', options: ['By restricting all student movement', 'By ensuring the campus remains a secure and peaceful place for learning', 'By managing academic examinations', 'By providing medical services'], correctAnswer: 'By ensuring the campus remains a secure and peaceful place for learning', order: 11 },
      { topicId: getTopicId('Security'), questionText: 'What should students present when requested by a security officer?', options: ['Their bank statement', 'Their student identification card', 'Their parent\'s phone number', 'Their JAMB result'], correctAnswer: 'Their student identification card', order: 12 },
      { topicId: getTopicId('Security'), questionText: 'Who does the Security Unit work closely with to ensure campus safety?', options: ['External police only', 'University management', 'JAMB officials', 'State government officials'], correctAnswer: 'University management', order: 13 },
      { topicId: getTopicId('Security'), questionText: 'How can students support the security team?', options: ['By taking over security duties', 'By providing useful information whenever necessary', 'By ignoring security rules', 'By reporting all classmates'], correctAnswer: 'By providing useful information whenever necessary', order: 14 },
      { topicId: getTopicId('Security'), questionText: 'What is the consequence of fighting on campus?', options: ['A verbal warning only', 'It is strictly prohibited and may lead to disciplinary action', 'It is allowed in certain areas', 'Security will mediate and allow it'], correctAnswer: 'It is strictly prohibited and may lead to disciplinary action', order: 15 },
      { topicId: getTopicId('Security'), questionText: 'Why must visitors register at the security gate?', options: ['To pay an entrance fee', 'To ensure campus security and proper monitoring of visitors', 'To obtain a library pass', 'To meet the DSA'], correctAnswer: 'To ensure campus security and proper monitoring of visitors', order: 16 },
      { topicId: getTopicId('Security'), questionText: 'What is the Security Unit\'s relationship with students?', options: ['Adversarial', 'Supportive — working to protect student safety and welfare', 'Neutral — they have no interaction with students', 'Only active during emergencies'], correctAnswer: 'Supportive — working to protect student safety and welfare', order: 17 },
      { topicId: getTopicId('Security'), questionText: 'What should a student do if their ID card is lost or stolen?', options: ['Continue without an ID card', 'Report to the appropriate university office and get a replacement', 'Use a photocopy of their ID', 'Borrow a classmate\'s ID card'], correctAnswer: 'Report to the appropriate university office and get a replacement', order: 18 },
      { topicId: getTopicId('Security'), questionText: 'Which of the following promotes a safe campus environment?', options: ['Ignoring suspicious activities', 'Cooperating with security and reporting suspicious activities', 'Bringing prohibited items to campus', 'Allowing unregistered visitors freely'], correctAnswer: 'Cooperating with security and reporting suspicious activities', order: 19 },
      { topicId: getTopicId('Security'), questionText: 'What is the overall goal of the University Security Unit?', options: ['To restrict student movement at all times', 'To maintain a safe, orderly and secure campus environment for all', 'To manage student academic performance', 'To replace the role of the DSA'], correctAnswer: 'To maintain a safe, orderly and secure campus environment for all', order: 20 },

      // ── GENERAL QUESTIONS ──────────────────────────────────────
      { topicId: getTopicId('General'), questionText: 'What type of university is Crawford University?', options: ['A federal government university', 'A private Christian university owned by the Apostolic Faith Church', 'A state government university', 'An international university'], correctAnswer: 'A private Christian university owned by the Apostolic Faith Church', order: 1 },
      { topicId: getTopicId('General'), questionText: 'Where is Crawford University located?', options: ['Lagos, Nigeria', 'Abuja, Nigeria', 'Igbesa, Ogun State, Nigeria', 'Ibadan, Oyo State, Nigeria'], correctAnswer: 'Igbesa, Ogun State, Nigeria', order: 2 },
      { topicId: getTopicId('General'), questionText: 'Which of the following is a compulsory activity for all Crawford University students?', options: ['Sports competitions', 'Chapel services', 'Library research', 'Political activities'], correctAnswer: 'Chapel services', order: 3 },
      { topicId: getTopicId('General'), questionText: 'What is the Sunday chapel schedule at Crawford University?', options: ['One service on Sunday morning only', 'Sunday morning service and Sunday evening service', 'Sunday afternoon service only', 'No chapel on Sundays'], correctAnswer: 'Sunday morning service and Sunday evening service', order: 4 },
      { topicId: getTopicId('General'), questionText: 'Which day has a midweek chapel service at Crawford University?', options: ['Monday', 'Tuesday', 'Wednesday', 'Thursday'], correctAnswer: 'Wednesday', order: 5 },
      { topicId: getTopicId('General'), questionText: 'What values does Crawford University expect all students to uphold?', options: ['Competition, ambition and wealth', 'Honesty, integrity, respect and responsibility', 'Independence, freedom and self expression', 'Fame, power and influence'], correctAnswer: 'Honesty, integrity, respect and responsibility', order: 6 },
      { topicId: getTopicId('General'), questionText: 'What is the environment at Crawford University committed to providing?', options: ['A purely academic environment with no social activities', 'Quality education within a disciplined and morally guided environment', 'A relaxed environment with minimal rules', 'An entertainment focused campus'], correctAnswer: 'Quality education within a disciplined and morally guided environment', order: 7 },
      { topicId: getTopicId('General'), questionText: 'What is the attendance policy for chapel services at Crawford University?', options: ['Optional for all students', 'Mandatory only for religious studies students', 'Compulsory for all students', 'Only compulsory for 100 level students'], correctAnswer: 'Compulsory for all students', order: 8 },
      { topicId: getTopicId('General'), questionText: 'How should students conduct themselves during chapel services?', options: ['They can talk freely during services', 'Respectfully during worship activities', 'They can use their phones freely', 'They can leave whenever they want'], correctAnswer: 'Respectfully during worship activities', order: 9 },
      { topicId: getTopicId('General'), questionText: 'Which church owns Crawford University?', options: ['The Catholic Church', 'The Anglican Church', 'The Apostolic Faith Church', 'The Baptist Church'], correctAnswer: 'The Apostolic Faith Church', order: 10 },
      { topicId: getTopicId('General'), questionText: 'What should students avoid to protect the reputation of Crawford University?', options: ['Attending chapel services', 'Any behavior that may bring disrepute to the institution', 'Participating in academic activities', 'Using the library regularly'], correctAnswer: 'Any behavior that may bring disrepute to the institution', order: 11 },
      { topicId: getTopicId('General'), questionText: 'What is the Wednesday chapel service called?', options: ['Sunday Morning Service', 'Wednesday Service', 'Midweek Revival', 'Prayer Meeting'], correctAnswer: 'Wednesday Service', order: 12 },
      { topicId: getTopicId('General'), questionText: 'Which of the following best describes Crawford University\'s mission?', options: ['To produce wealthy graduates only', 'To provide quality education in a disciplined and morally guided environment', 'To be the largest university in Nigeria', 'To focus only on science and technology courses'], correctAnswer: 'To provide quality education in a disciplined and morally guided environment', order: 13 },
      { topicId: getTopicId('General'), questionText: 'What must students obey throughout their time at Crawford University?', options: ['Only the rules they agree with', 'All university rules and regulations', 'Only the rules of their department', 'Only the rules during examination periods'], correctAnswer: 'All university rules and regulations', order: 14 },
      { topicId: getTopicId('General'), questionText: 'Which of the following is an important part of university life at Crawford?', options: ['Political campaigns', 'Chapel services and spiritual development', 'Commercial business activities', 'Entertainment industry involvement'], correctAnswer: 'Chapel services and spiritual development', order: 15 },
      { topicId: getTopicId('General'), questionText: 'What is the state in which Crawford University is located?', options: ['Lagos State', 'Ogun State', 'Osun State', 'Ondo State'], correctAnswer: 'Ogun State', order: 16 },
      { topicId: getTopicId('General'), questionText: 'What kind of institution does Crawford University aim to be?', options: ['A purely commercial institution', 'An institution committed to academic excellence and moral values', 'An institution focused only on postgraduate programs', 'An institution with no religious affiliation'], correctAnswer: 'An institution committed to academic excellence and moral values', order: 17 },
      { topicId: getTopicId('General'), questionText: 'What behavior is expected of students during chapel services?', options: ['Casual and relaxed behavior', 'Respectful conduct during all worship activities', 'Use of mobile phones is permitted', 'Attendance is optional'], correctAnswer: 'Respectful conduct during all worship activities', order: 18 },
      { topicId: getTopicId('General'), questionText: 'How many chapel services are held on Sundays at Crawford University?', options: ['One', 'Two', 'Three', 'None'], correctAnswer: 'Two', order: 19 },
      { topicId: getTopicId('General'), questionText: 'What is expected of students regarding university property?', options: ['They can use it however they like', 'They must respect and protect university property at all times', 'Only staff are responsible for university property', 'Students have no responsibility for university property'], correctAnswer: 'They must respect and protect university property at all times', order: 20 },

    ];

    // Filter out questions with null topicId
    const validQuestions = questions.filter(q => {
      if (!q.topicId) {
        console.log(`Warning: No topic found for a question — skipping`);
        return false;
      }
      return true;
    });

    await Question.insertMany(validQuestions);
    console.log(`Successfully seeded ${validQuestions.length} questions!`);
    process.exit();
  } catch (error) {
    console.error('Error:', error.message);
    process.exit(1);
  }
};

seedQuestions();